In [1]:
#prezicera nivelului apei in cm a Lacului Beleu

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_excel('beleu_regim_hidrologic.xlsx')
df

           Ziua  Regimul hidrologic in cm
0    2015-01-01                       198
1    2015-01-02                       193
2    2015-01-03                       189
3    2015-01-04                       185
4    2015-01-05                       181
...         ...                       ...
2187 2020-12-27                        69
2188 2020-12-28                        69
2189 2020-12-29                        69
2190 2020-12-30                        71
2191 2020-12-31                        73

[2192 rows x 2 columns]

In [4]:
# creem variabile pentru prezicerea in zile a viitorului
projection = 365
#creem coloana care prezicem
df['Prezicere'] = df[['Regimul hidrologic in cm']].shift(-projection)
#vedem rezultatul
df

           Ziua  Regimul hidrologic in cm  Prezicere
0    2015-01-01                       198       38.0
1    2015-01-02                       193       38.0
2    2015-01-03                       189       38.0
3    2015-01-04                       185       38.0
4    2015-01-05                       181       38.0
...         ...                       ...        ...
2187 2020-12-27                        69        NaN
2188 2020-12-28                        69        NaN
2189 2020-12-29                        69        NaN
2190 2020-12-30                        71        NaN
2191 2020-12-31                        73        NaN

[2192 rows x 3 columns]

In [5]:
#creem data setul independent (x)
X = np.array(df[['Regimul hidrologic in cm']])
#stergem ultimele 365 rinduri
X = X[:-projection]
print(X)

[[198]
 [193]
 [189]
 ...
 [ 39]
 [ 39]
 [ 39]]

In [6]:
#creem un data set (y)
y = df['Prezicere'].values
y = y[:-projection]
print(y)

[38. 38. 38. ... 69. 71. 73.]

In [8]:
# despartim datele in 85% antrenare si 15% antrenare
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= .365)

In [9]:
#creem un model de antrenare
linReg = LinearRegression()
#antrenam modelul
linReg.fit(X_train, y_train)

LinearRegression()

In [10]:
#testam modelul folosind scorul
linReg_confidence = linReg.score(X_test, y_test)
print('Linear regression Confidence:', linReg_confidence)

Linear regression Confidence: 0.11179643751215862

In [11]:
#creem o variabila x_projection pentru ultimele 365 de rinduri din data setul original
x_projection = np.array(df[['Regimul hidrologic in cm']])[-projection:]
print(x_projection)

[[ 39]
 [ 39]
 [ 39]
 [ 39]
 [ 39]
 [ 39]
 [ 39]
 [ 39]
 [ 39]
 [ 39]
 [ 38]
 [ 38]
 [ 38]
 [ 38]
 [ 38]
 [ 37]
 [ 37]
 [ 37]
 [ 37]
 [ 37]
 [ 37]
 [ 36]
 [ 36]
 [ 36]
 [ 36]
 [ 36]
 [ 36]
 [ 35]
 [ 35]
 [ 35]
 [ 35]
 [ 34]
 [ 34]
 [ 34]
 [ 33]
 [ 33]
 [ 33]
 [ 33]
 [ 33]
 [ 33]
 [ 32]
 [ 32]
 [ 32]
 [ 32]
 [ 32]
 [ 31]
 [ 31]
 [ 31]
 [ 31]
 [ 31]
 [ 31]
 [ 30]
 [ 30]
 [ 30]
 [ 32]
 [ 33]
 [ 35]
 [ 37]
 [ 40]
 [ 44]
 [ 48]
 [ 55]
 [ 59]
 [ 60]
 [ 61]
 [ 64]
 [ 69]
 [ 70]
 [ 72]
 [ 81]
 [ 85]
 [ 93]
 [ 97]
 [101]
 [115]
 [120]
 [121]
 [121]
 [121]
 [121]
 [119]
 [117]
 [102]
 [ 94]
 [ 82]
 [ 79]
 [ 75]
 [ 71]
 [ 68]
 [ 62]
 [ 53]
 [ 48]
 [ 47]
 [ 44]
 [ 41]
 [ 39]
 [ 38]
 [ 37]
 [ 35]
 [ 35]
 [ 32]
 [ 30]
 [ 29]
 [ 29]
 [ 28]
 [ 28]
 [ 26]
 [ 25]
 [ 24]
 [ 23]
 [ 20]
 [ 20]
 [ 19]
 [ 19]
 [ 19]
 [ 19]
 [ 19]
 [ 19]
 [ 20]
 [ 20]
 [ 21]
 [ 22]
 [ 22]
 [ 22]
 [ 23]
 [ 23]
 [ 23]
 [ 23]
 [ 23]
 [ 24]
 [ 24]
 [ 26]
 [ 26]
 [ 28]
 [ 28]
 [ 28]
 [ 29]
 [ 29]
 [ 29]
 [ 30]
 [ 31]
 [ 31]
 [ 32]
 [ 32]
 [ 33]
 [ 33]
 [ 34]
 [ 34]
 [ 35]
 [ 35]
 [ 35]
 [ 36]
 [ 37]
 [ 37]
 [ 38]
 [ 38]
 [ 38]
 [ 42]
 [ 47]
 [ 59]
 [ 67]
 [ 60]
 [ 78]
 [ 82]
 [ 85]
 [ 89]
 [ 91]
 [ 95]
 [ 97]
 [ 99]
 [105]
 [106]
 [107]
 [109]
 [110]
 [115]
 [120]
 [125]
 [132]
 [140]
 [146]
 [158]
 [167]
 [175]
 [189]
 [194]
 [203]
 [205]
 [211]
 [232]
 [255]
 [274]
 [295]
 [313]
 [322]
 [329]
 [350]
 [350]
 [350]
 [350]
 [345]
 [332]
 [328]
 [301]
 [283]
 [264]
 [240]
 [227]
 [213]
 [202]
 [195]
 [181]
 [168]
 [165]
 [164]
 [163]
 [160]
 [159]
 [159]
 [158]
 [157]
 [156]
 [155]
 [155]
 [146]
 [140]
 [137]
 [132]
 [129]
 [127]
 [124]
 [120]
 [118]
 [118]
 [117]
 [116]
 [110]
 [109]
 [108]
 [108]
 [107]
 [106]
 [104]
 [100]
 [ 98]
 [ 92]
 [ 90]
 [ 90]
 [ 89]
 [ 88]
 [ 86]
 [ 85]
 [ 83]
 [ 81]
 [ 79]
 [ 78]
 [ 76]
 [ 76]
 [ 75]
 [ 74]
 [ 72]
 [ 70]
 [ 68]
 [ 67]
 [ 67]
 [ 66]
 [ 66]
 [ 65]
 [ 65]
 [ 65]
 [ 64]
 [ 64]
 [ 63]
 [ 62]
 [ 62]
 [ 62]
 [ 61]
 [ 61]
 [ 61]
 [ 61]
 [ 60]
 [ 60]
 [ 60]
 [ 60]
 [ 60]
 [ 60]
 [ 60]
 [ 60]
 [ 60]
 [ 61]
 [ 61]
 [ 61]
 [ 62]
 [ 63]
 [ 67]
 [ 69]
 [ 71]
 [ 75]
 [ 77]
 [ 80]
 [ 81]
 [ 82]
 [ 83]
 [ 84]
 [ 84]
 [ 84]
 [ 84]
 [ 84]
 [ 84]
 [ 83]
 [ 83]
 [ 83]
 [ 83]
 [ 83]
 [ 83]
 [ 83]
 [ 82]
 [ 82]
 [ 82]
 [ 81]
 [ 81]
 [ 81]
 [ 81]
 [ 81]
 [ 80]
 [ 80]
 [ 80]
 [ 80]
 [ 80]
 [ 79]
 [ 79]
 [ 79]
 [ 79]
 [ 78]
 [ 77]
 [ 77]
 [ 77]
 [ 77]
 [ 77]
 [ 77]
 [ 77]
 [ 76]
 [ 76]
 [ 76]
 [ 75]
 [ 75]
 [ 75]
 [ 75]
 [ 74]
 [ 73]
 [ 73]
 [ 72]
 [ 72]
 [ 71]
 [ 71]
 [ 71]
 [ 70]
 [ 70]
 [ 70]
 [ 69]
 [ 69]
 [ 69]
 [ 69]
 [ 71]
 [ 73]]

In [12]:
# afisam prezicerea pentru pentru urm 365 zile
linReg_prediction = linReg.predict(x_projection)
print(linReg_prediction)

[ 82.97459009  82.97459009  82.97459009  82.97459009  82.97459009
  82.97459009  82.97459009  82.97459009  82.97459009  82.97459009
  82.59443923  82.59443923  82.59443923  82.59443923  82.59443923
  82.21428837  82.21428837  82.21428837  82.21428837  82.21428837
  82.21428837  81.83413751  81.83413751  81.83413751  81.83413751
  81.83413751  81.83413751  81.45398664  81.45398664  81.45398664
  81.45398664  81.07383578  81.07383578  81.07383578  80.69368492
  80.69368492  80.69368492  80.69368492  80.69368492  80.69368492
  80.31353406  80.31353406  80.31353406  80.31353406  80.31353406
  79.93338319  79.93338319  79.93338319  79.93338319  79.93338319
  79.93338319  79.55323233  79.55323233  79.55323233  80.31353406
  80.69368492  81.45398664  82.21428837  83.35474095  84.8753444
  86.39594785  89.05700389  90.57760734  90.9577582   91.33790906
  92.47836165  94.37911596  94.75926682  95.51956855  98.94092631
 100.46152976 103.50273666 105.0233401  106.54394355 111.86605563
 113.76680994 114.1469608  114.1469608  114.1469608  114.1469608
 113.38665907 112.62635735 106.92409442 103.88288752  99.32107717
  98.18062458  96.66002113  95.13941769  93.9989651   91.71805992
  88.29670216  86.39594785  86.01579699  84.8753444   83.73489182
  82.97459009  82.59443923  82.21428837  81.45398664  81.45398664
  80.31353406  79.55323233  79.17308147  79.17308147  78.79293061
  78.79293061  78.03262888  77.65247802  77.27232716  76.8921763
  75.75172371  75.75172371  75.37157285  75.37157285  75.37157285
  75.37157285  75.37157285  75.37157285  75.75172371  75.75172371
  76.13187457  76.51202543  76.51202543  76.51202543  76.8921763
  76.8921763   76.8921763   76.8921763   76.8921763   77.27232716
  77.27232716  78.03262888  78.03262888  78.79293061  78.79293061
  78.79293061  79.17308147  79.17308147  79.17308147  79.55323233
  79.93338319  79.93338319  80.31353406  80.31353406  80.69368492
  80.69368492  81.07383578  81.07383578  81.45398664  81.45398664
  81.45398664  81.83413751  82.21428837  82.21428837  82.59443923
  82.59443923  82.59443923  84.11504268  86.01579699  90.57760734
  93.61881424  90.9577582   97.80047372  99.32107717 100.46152976
 101.98213321 102.74243493 104.26303838 105.0233401  105.78364183
 108.064547   108.44469787 108.82484873 109.58515045 109.96530131
 111.86605563 113.76680994 115.66756425 118.32862028 121.36982718
 123.65073236 128.2125427  131.63390046 134.67510736 139.99721943
 141.89797375 145.31933151 146.07963323 148.3605384  156.34370651
 165.08717634 172.31004273 180.29321084 187.13592636 190.55728412
 193.21834015 201.20150826 201.20150826 201.20150826 201.20150826
 199.30075395 194.35879274 192.83818929 182.57411601 175.73140049
 168.5085341  159.38491341 154.4429522  149.12084013 144.93918064
 142.27812461 136.95601254 132.01405133 130.87359874 130.49344788
 130.11329701 128.97284443 128.59269357 128.59269357 128.2125427
 127.83239184 127.45224098 127.07209012 127.07209012 123.65073236
 121.36982718 120.2293746  118.32862028 117.1881677  116.42786597
 115.28741339 113.76680994 113.00650821 113.00650821 112.62635735
 112.24620649 109.96530131 109.58515045 109.20499959 109.20499959
 108.82484873 108.44469787 107.68439614 106.16379269 105.40349097
 103.12258579 102.36228407 102.36228407 101.98213321 101.60198234
 100.84168062 100.46152976  99.70122803  98.94092631  98.18062458
  97.80047372  97.040172    97.040172    96.66002113  96.27987027
  95.51956855  94.75926682  93.9989651   93.61881424  93.61881424
  93.23866337  93.23866337  92.85851251  92.85851251  92.85851251
  92.47836165  92.47836165  92.09821079  91.71805992  91.71805992
  91.71805992  91.33790906  91.33790906  91.33790906  91.33790906
  90.9577582   90.9577582   90.9577582   90.9577582   90.9577582
  90.9577582   90.9577582   90.9577582   90.9577582   91.33790906
  91.33790906  91.33790906  91.71805992  92.09821079  93.61881424
  94.37911596  95.13941769  96.66002113  97.42032286  98.56077545
  98.94092631  99.32107717  99.70122803 100.0813789  100.0813789
 100.0813789  100.0813789  100.0813789  100.0813789   99.70122803
  99.70122803  99.70122803  99.70122803  99.70122803  99.70122803
  99.70122803  99.32107717  99.32107717  99.32107717  98.94092631
  98.94092631  98.94092631  98.94092631  98.94092631  98.56077545
  98.56077545  98.56077545  98.56077545  98.56077545  98.18062458
  98.18062458  98.18062458  98.18062458  97.80047372  97.42032286
  97.42032286  97.42032286  97.42032286  97.42032286  97.42032286
  97.42032286  97.040172    97.040172    97.040172    96.66002113
  96.66002113  96.66002113  96.66002113  96.27987027  95.89971941
  95.89971941  95.51956855  95.51956855  95.13941769  95.13941769
  95.13941769  94.75926682  94.75926682  94.75926682  94.37911596
  94.37911596  94.37911596  94.37911596  95.13941769  95.89971941]